/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useThree, useFrame } from "@react-three/fiber";

export default function Model(props) {
  const mesh = useRef();
  const { nodes, materials } = useGLTF("/bunny-baked2.glb");
  const { viewport } = useThree();
  const [hover, setHover] = useState(false);
  const [reset, setReset] = useState(false);
  var passedTime = 0;
  var move = false;

  useFrame((state, delta) => {
    if (hover && !reset) {
      setReset(true);
      passedTime = 0;
    } else if (hover) {
      passedTime += 0.01;
    }
    if (hover && passedTime % (Math.PI / 10) <= 0.01) {
      move = !move;
    }
    mesh.current.rotation.z +=
      Math.sin(passedTime * 20) * (hover ? 0.005 : 0) * move;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={mesh}
        castShadow
        receiveShadow
        geometry={nodes.Bunny_Scene.geometry}
        material={materials.palette}
        rotation={[Math.PI / 2, 0, 0]}
        position={[0, -1.5, 1]}
        scale={viewport.width / 6}
        onPointerOver={(e) => setHover(true)}
        onPointerLeave={(e) => {
          setHover(false);
          setReset(false);
          move = false;
          mesh.current.rotation.z = 0;
        }}
      />
    </group>
  );
}

useGLTF.preload("/bunny-baked2.glb");
