import Head from "next/head";
import { Suspense } from "react";
import { Canvas } from "@react-three/fiber";

import BunnyModel from "../components/BunnyModel";
import {
  HomeWrapper,
  ThumbnailSection,
  Heading,
  IntroductionSection,
} from "../styles/HomeStyle";
import { EmphasizedText } from "../styles/SharedStyle";
import { pageTransition } from "../lib/animation";

export default function Home() {
  return (
    <HomeWrapper
      variants={pageTransition}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NavItem_Me_Active.svg" />
      </Head>

      <ThumbnailSection>
        <Canvas orthographic camera={{ zoom: 50, position: [-5, 2, 5] }}>
          <ambientLight intensity={0.8} />
          <Suspense fallback={null}>
            <BunnyModel />
          </Suspense>
          <mesh rotation={[-Math.PI / 2, 0, 0]} position={[0, -1.5, 0]}>
            <circleGeometry args={[2, 16, 0, 2 * Math.PI]} />
            <meshBasicMaterial color={0xe0c5a8} toneMapped={false} />
          </mesh>
          {/* <OrbitControls /> */}
        </Canvas>
      </ThumbnailSection>
      <IntroductionSection
        initial={{ opacity: 0, x: 50 }}
        animate={{ opacity: 1, x: 0, transition: { delay: 0.3 } }}
      >
        <Heading>
          Hello! I&apos;m baibai, I make{" "}
          <EmphasizedText color="#E48BBA">websites</EmphasizedText>,{" "}
          <span>
            and other interactive stuff like{" "}
            <a href="https://baibaiya.itch.io">games</a>
          </span>
        </Heading>

        <p className="">
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloribus,
          voluptatibus in. Enim quisquam dignissimos perferendis non, expedita,
          quam dolor explicabo sequi nihil commodi assumenda autem atque
          pariatur, porro reprehenderit possimus?
        </p>
      </IntroductionSection>
    </HomeWrapper>
  );
}
