import Head from "next/head";
import Link from "next/link";
import { Suspense, useRef } from "react";
import { Canvas } from "@react-three/fiber";

import BunnyModel from "../components/BunnyModel";
import {
  HomeWrapper,
  ThumbnailSection,
  Heading,
  IntroductionSection,
  CallToAction,
} from "../styles/HomeStyle";
import { EmphasizedText } from "../styles/SharedStyle";
import { pageTransition } from "../lib/animation";
import { useSpring, animated } from "@react-spring/three";
import { useEffect } from "react";
import { OrbitControls } from "@react-three/drei";

import { LiveSiteButton } from "../styles/WorkDetailsStyle";

export default function Home() {
  const circleMesh = useRef(null);

  const [spring, api] = useSpring(
    () => ({ scale: 0, config: { mass: 2, tension: 300 } }),
    []
  );

  useEffect(() => {
    api.start({ scale: 1 });
    console.log(circleMesh.current);
  });

  return (
    <HomeWrapper
      variants={pageTransition}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NavItem_Me_Active.svg" />
      </Head>

      <ThumbnailSection>
        <Canvas orthographic camera={{ zoom: 50, position: [-5, 2, 5] }}>
          <ambientLight intensity={0.8} />
          <Suspense fallback={null}>
            <BunnyModel />
          </Suspense>

          <OrbitControls
            enablePan={false}
            minPolarAngle={Math.PI / 2.4}
            maxPolarAngle={Math.PI / 2.4}
          />
        </Canvas>
      </ThumbnailSection>
      <IntroductionSection
        initial={{ opacity: 0, x: 50 }}
        animate={{ opacity: 1, x: 0, transition: { delay: 0.3 } }}
      >
        <Heading>
          Hi! I&apos;m Bethany, I design and create interactive{" "}
          <span>
            experiences with{" "}
            <EmphasizedText color="#E48BBA">websites</EmphasizedText> and{" "}
            <a href="https://baibaiya.itch.io">games</a>.
          </span>
          {/* Hello! I&apos;m baibai, I make{" "}
          <EmphasizedText color="#E48BBA">websites</EmphasizedText>,{" "}
          <span>
            and other interactive stuff like{" "}
            <a href="https://baibaiya.itch.io">games</a>
          </span> */}
        </Heading>

        <p className="">
          With a background in coding and game design, and a strong interest in
          music and art, I have been keen on seeking innovative intersections of
          art and technology. I wish to create experiences that emotionally
          connect with people.
        </p>

        {/* <Link href={"/project"}>
          <CallToAction>
            <button>
              Projects <span>&#62;</span>
            </button>
          </CallToAction>
        </Link> */}
      </IntroductionSection>
    </HomeWrapper>
  );
}
