import Head from "next/head";
import { Suspense } from "react";
import { Canvas } from "@react-three/fiber";

import BunnyModel from "../components/BunnyModel";
import {
  HomeWrapper,
  ThumbnailSection,
  Heading,
  IntroductionSection,
} from "../styles/HomeStyle";
import { EmphasizedText } from "../styles/SharedStyle";
import { pageTransition } from "../lib/animation";
import { useSpring, animated } from "@react-spring/three";
import { useEffect } from "react";
import { OrbitControls } from "@react-three/drei";

export default function Home() {
  const [spring, api] = useSpring(
    () => ({ scale: 0, config: { mass: 2, tension: 300 } }),
    []
  );

  useEffect(() => {
    api.start({ scale: 1 });
  });

  return (
    <HomeWrapper
      variants={pageTransition}
      initial="initial"
      animate="animate"
      exit="exit"
    >
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/NavItem_Me_Active.svg" />
      </Head>

      <ThumbnailSection>
        <Canvas orthographic camera={{ zoom: 50, position: [-5, 2, 5] }}>
          <ambientLight intensity={0.8} />
          <Suspense fallback={null}>
            <BunnyModel />
          </Suspense>
          <animated.mesh
            {...spring}
            rotation={[-Math.PI / 2, 0, 0]}
            position={[0, -1.5, 0]}
          >
            <circleGeometry args={[2, 16, 0, 2 * Math.PI]} />
            <meshBasicMaterial color={0xe0c5a8} toneMapped={false} />
          </animated.mesh>
          <OrbitControls
            enablePan={false}
            minPolarAngle={Math.PI / 2.4}
            maxPolarAngle={Math.PI / 2.4}
          />
        </Canvas>
      </ThumbnailSection>
      <IntroductionSection
        initial={{ opacity: 0, x: 50 }}
        animate={{ opacity: 1, x: 0, transition: { delay: 0.3 } }}
      >
        <Heading>
          Hello! I&apos;m baibai, I create interactive digital{" "}
          <span>
            experiences with{" "}
            <EmphasizedText color="#E48BBA">websites</EmphasizedText> and{" "}
            <a href="https://baibaiya.itch.io">games</a>
          </span>
          {/* Hello! I&apos;m baibai, I make{" "}
          <EmphasizedText color="#E48BBA">websites</EmphasizedText>,{" "}
          <span>
            and other interactive stuff like{" "}
            <a href="https://baibaiya.itch.io">games</a>
          </span> */}
        </Heading>

        <p className="">
          With a background in Computer Science, and a long lasting interest in
          music and art, I have been exploring ways to combine them that lead to
          interesting and unique experiences. Currently, the areas that I am
          most keen on are 3d animation, webgl and adaptive audio.
        </p>
      </IntroductionSection>
    </HomeWrapper>
  );
}
